on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 12 15 * *'

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths_ignore: '["**/*.md"]'

  chain:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        run: bash ./gradlew check
